##开启日志DEBUG级别，便于查看调试信息
logging.level.org.springframework.security: DEBUG
server:
  port: 9996
spring:
  #系统名称
  application:
    name: business-server
  #微服务配置
  cloud:
    nacos:
      username: nacos
      password: nacos
      #注册中心
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
